//the internal error after the function is the closure
//a function within a function
